server:
  port: 8761

spring.cloud.config.discovery.enabled: true
spring:
  application:
    name: discovery-server

eureka.instance.instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
  server:
    enableSelfPreservation: false
endpoints:
  health:
    sensitive: true
    # renewalPercentThreshold: 0.49
    # renewalThresholdUpdateIntervalMs

    # Set this only for this sample service without which starting the instance will by default wait for the default of 5 mins
#    waitTimeInMsWhenSyncEmpty: 0

    # for the example, set this to zero as we will not have peers to sync up with.
    # Do not set in a real environment with multi-node eureka clusters.
#    numberRegistrySyncRetries: 0

#    response-cache-update-interval-ms: 1000
#  password: ${SECURITY_USER_PASSWORD:password}

#扫描失效服务的间隔时间（缺省为60*1000ms）
eureka.server.eviction-interval-timer-in-ms: 30000

